# This file was generated by GoReleaser. DO NOT EDIT.
cask "fhirlint" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "e3947fc0c2e17966a78de759621da929037bc189cb24da21a11bc09990d82728"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea249da52f6457c984e79ba5a5c7e233cddc51225d6638eda5077e380d6c37a5"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d897571b4e6ff0355ef2085f7503b356fcbb9f0ea461fefdbe3d4fd950a67039"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "464abc512c027d111eb8be470ddb89d65bd87af04d96168d021e3fea935a1abf"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fhirlint"
  desc "Lightweight CLI for validating FHIR resources against profiles and implementation guides"
  homepage "https://github.com/fhirlint/fhirlint"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openjdk@17",
    ]

  binary "fhirlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fhirlint"]
    end
  end

  # No zap stanza required

end
