# This file was generated by GoReleaser. DO NOT EDIT.
cask "fhirlint" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "bc77aa95a151275f636b08e97afa1e06e7536190b995082b62c8806f9ea490a7"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2362b3605dd62c52e7da7ad2a59be8717c8ecdfb29e36eed047386327e2513b"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d15e18b75261abe53e7d1f17c6992e6b225b319d795c1429b455fd33766ab40"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a75e6ddb0b3872bb14583aaf969f475bf3617f682c649ee841d8a24817e2ea5"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fhirlint"
  desc "Lightweight CLI for validating FHIR resources against profiles and implementation guides"
  homepage "https://github.com/fhirlint/fhirlint"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openjdk@17",
    ]

  binary "fhirlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fhirlint"]
    end
  end

  # No zap stanza required

end
