# This file was generated by GoReleaser. DO NOT EDIT.
cask "fhirlint" do
  version "1.12.1"

  on_macos do
    on_arm do
      sha256 "5e22c9fb04a9ba9f190c1746fbbc78ea075046bbe725b59c3465c0fce697b8d4"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5958c70e501e7d158aa97bea42c65c1301d2c7dc211f8c3ca3785ddf2c4afd6e"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b251b3b5b332eab2f5d47a58beb37f0e5080712bf952980d99aaa47a78c804fb"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31b7a365304cffbf08703e88ae675d80ff45b465355635547774d7243038c4b4"
      url "https://github.com/fhirlint/fhirlint/releases/download/v#{version}/fhirlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "fhirlint"
  desc "Lightweight CLI for validating FHIR resources against profiles and implementation guides"
  homepage "https://github.com/fhirlint/fhirlint"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openjdk@17",
    ]

  binary "fhirlint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fhirlint"]
    end
  end

  # No zap stanza required
end
